//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabulaLasec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animales
    {
        public long idAnimal { get; set; }
        public string Nombre { get; set; }
        public int Velocidad { get; set; }
        public string Resultado { get; set; }
        public long idCarrera { get; set; }
        public Nullable<int> TiempoRecorrido { get; set; }
    }
}
